// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByo4Q3R5CX2JWdCa3Cg5sR02ot1_2xMzQ',
    appId: '1:521674901512:web:01e92cd486a61a4f2d29bd',
    messagingSenderId: '521674901512',
    projectId: 'gr09-studyearly-fall-2025',
    authDomain: 'gr09-studyearly-fall-2025.firebaseapp.com',
    storageBucket: 'gr09-studyearly-fall-2025.firebasestorage.app',
    measurementId: 'G-7RS3L112XF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1gxNWxzS6wekV7kszpuXU3GUdqMCVxzE',
    appId: '1:521674901512:android:fb6e9147d54e7f3a2d29bd',
    messagingSenderId: '521674901512',
    projectId: 'gr09-studyearly-fall-2025',
    storageBucket: 'gr09-studyearly-fall-2025.firebasestorage.app',
  );
}